name: Update Readme

on:
  push:
    paths:
      - 'docs/index.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy index.md to README.md
        run: cp docs/index.md README.md

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update README.md from docs/index.md" || echo "No changes to commit"
          git push origin ${{ github.ref }}